name: CI

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: test shell code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install shellcheck
        run: sudo apt install shellcheck
      - name: find scripts
        run: echo "SCRIPTS=$(find $GITHUB_WORKSPACE -name '*.sh')" >> "$GITHUB_OUTPUT"
        id: scripts-lookup
      - name: test code
        run: shellcheck ${{ steps.scripts-lookup.outputs.SCRIPTS }}
        if:  ${{ contains(steps.scripts-lookup.outputs.SCRIPTS,'sh') }}
